version: "1.1.0"
services:
  api:
    build: Dockerfile
    contexnt: .
  depends_on:
  environment:
    ENV DATABASE_URL: postgresql://looknote:khc3261211923@looknote-db-prod.ccjd96mru7oe.ap-northeast-2.rds.amazonaws.com:5432/postgres?schema=public
    NODE_ENV: prod
    PORT: 8000
  ports:
    - "8080:8000"